// <auto-generated />
using System;
using KargoTakibi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KargoTakibi.Migrations
{
    [DbContext(typeof(KargoTakipContext))]
    partial class KargoTakipContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KargoTakibi.Models.Hareket", b =>
                {
                    b.Property<int>("HareketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HareketID"), 1L, 1);

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KargoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("HareketID");

                    b.HasIndex("KargoID");

                    b.ToTable("Hareketler");
                });

            modelBuilder.Entity("KargoTakibi.Models.Kargo", b =>
                {
                    b.Property<int>("KargoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KargoID"), 1L, 1);

                    b.Property<string>("AliciAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AliciAdresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AliciIl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AliciIlce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AliciTelefonu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Durum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GondericiAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GondericiAdresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GondericiIl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GondericiIlce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GondericiTelefonu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KullaniciID")
                        .HasColumnType("int");

                    b.HasKey("KargoID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Kargolar");
                });

            modelBuilder.Entity("KargoTakibi.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciID"), 1L, 1);

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciID");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("KargoTakibi.Models.Hareket", b =>
                {
                    b.HasOne("KargoTakibi.Models.Kargo", "Kargo")
                        .WithMany("Hareketler")
                        .HasForeignKey("KargoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kargo");
                });

            modelBuilder.Entity("KargoTakibi.Models.Kargo", b =>
                {
                    b.HasOne("KargoTakibi.Models.Kullanici", "Kullanici")
                        .WithMany("Kargolar")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("KargoTakibi.Models.Kargo", b =>
                {
                    b.Navigation("Hareketler");
                });

            modelBuilder.Entity("KargoTakibi.Models.Kullanici", b =>
                {
                    b.Navigation("Kargolar");
                });
#pragma warning restore 612, 618
        }
    }
}
